import type { Chart, ChartKey, ChartSnapshot, Planet } from "@/lib/schemas";

const signs = [
  "Aries",
  "Taurus",
  "Gemini",
  "Cancer",
  "Leo",
  "Virgo",
  "Libra",
  "Scorpio",
  "Sagittarius",
  "Capricorn",
  "Aquarius",
  "Pisces",
] as const;

const signLords: Record<(typeof signs)[number], Planet> = {
  Aries: "Mars",
  Taurus: "Venus",
  Gemini: "Mercury",
  Cancer: "Moon",
  Leo: "Sun",
  Virgo: "Mercury",
  Libra: "Venus",
  Scorpio: "Mars",
  Sagittarius: "Jupiter",
  Capricorn: "Saturn",
  Aquarius: "Saturn",
  Pisces: "Jupiter",
};

const planets: Planet[] = ["Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus", "Saturn", "Rahu", "Ketu"];

type PlacementMap = Record<Planet, { sign: string; house: number }>;

function makeHouses(ascendantSign: (typeof signs)[number]) {
  const startIndex = signs.indexOf(ascendantSign);
  return Array.from({ length: 12 }, (_, index) => {
    const sign = signs[(startIndex + index) % signs.length] ?? "Aries";
    return {
      house: index + 1,
      sign,
      lord: signLords[sign],
    };
  });
}

function makeChart(chartKey: ChartKey, ascendantSign: (typeof signs)[number], placements: PlacementMap): Chart {
  return {
    chart_key: chartKey,
    ascendant_sign: ascendantSign,
    houses: makeHouses(ascendantSign),
    planets: planets.map((planet) => ({
      planet,
      sign: placements[planet].sign,
      house: placements[planet].house,
    })),
  };
}

const d1Placements: PlacementMap = {
  Sun: { sign: "Taurus", house: 4 },
  Moon: { sign: "Virgo", house: 8 },
  Mars: { sign: "Leo", house: 7 },
  Mercury: { sign: "Taurus", house: 4 },
  Jupiter: { sign: "Scorpio", house: 10 },
  Venus: { sign: "Taurus", house: 4 },
  Saturn: { sign: "Pisces", house: 2 },
  Rahu: { sign: "Libra", house: 9 },
  Ketu: { sign: "Aries", house: 3 },
};

export const goldenSnapshot: ChartSnapshot = {
  id: "00000000-0000-4000-8000-000000000099",
  birth_profile_id: "00000000-0000-4000-8000-000000000001",
  engine_version: "astro_engine_v1",
  computed_at: "2020-01-01T00:00:00Z",
  birth_time_confidence: "exact",
  summary: {
    lagna: "Aquarius",
    moon_sign: "Virgo",
    nakshatra: "Uttara Phalguni",
    pada: 4,
  },
  charts: {
    D1: makeChart("D1", "Aquarius", d1Placements),
    Bhava: makeChart("Bhava", "Aquarius", d1Placements),
    Moon: makeChart("Moon", "Virgo", {
      Sun: { sign: "Taurus", house: 9 },
      Moon: { sign: "Virgo", house: 1 },
      Mars: { sign: "Leo", house: 12 },
      Mercury: { sign: "Taurus", house: 9 },
      Jupiter: { sign: "Scorpio", house: 3 },
      Venus: { sign: "Taurus", house: 9 },
      Saturn: { sign: "Pisces", house: 7 },
      Rahu: { sign: "Libra", house: 2 },
      Ketu: { sign: "Aries", house: 8 },
    }),
    D2: makeChart("D2", "Sagittarius", {
      Sun: { sign: "Gemini", house: 7 },
      Moon: { sign: "Pisces", house: 4 },
      Mars: { sign: "Sagittarius", house: 1 },
      Mercury: { sign: "Gemini", house: 7 },
      Jupiter: { sign: "Gemini", house: 7 },
      Venus: { sign: "Cancer", house: 8 },
      Saturn: { sign: "Pisces", house: 4 },
      Rahu: { sign: "Aries", house: 5 },
      Ketu: { sign: "Aries", house: 5 },
    }),
    D3: makeChart("D3", "Aquarius", {
      Sun: { sign: "Capricorn", house: 12 },
      Moon: { sign: "Virgo", house: 8 },
      Mars: { sign: "Sagittarius", house: 11 },
      Mercury: { sign: "Virgo", house: 8 },
      Jupiter: { sign: "Pisces", house: 2 },
      Venus: { sign: "Taurus", house: 4 },
      Saturn: { sign: "Pisces", house: 2 },
      Rahu: { sign: "Libra", house: 9 },
      Ketu: { sign: "Aries", house: 3 },
    }),
    D4: makeChart("D4", "Aquarius", {
      Sun: { sign: "Aquarius", house: 1 },
      Moon: { sign: "Sagittarius", house: 11 },
      Mars: { sign: "Scorpio", house: 10 },
      Mercury: { sign: "Scorpio", house: 10 },
      Jupiter: { sign: "Taurus", house: 4 },
      Venus: { sign: "Taurus", house: 4 },
      Saturn: { sign: "Pisces", house: 2 },
      Rahu: { sign: "Capricorn", house: 12 },
      Ketu: { sign: "Cancer", house: 6 },
    }),
    D6: makeChart("D6", "Taurus", {
      Sun: { sign: "Aquarius", house: 10 },
      Moon: { sign: "Scorpio", house: 7 },
      Mars: { sign: "Gemini", house: 2 },
      Mercury: { sign: "Capricorn", house: 9 },
      Jupiter: { sign: "Capricorn", house: 9 },
      Venus: { sign: "Libra", house: 6 },
      Saturn: { sign: "Libra", house: 6 },
      Rahu: { sign: "Taurus", house: 1 },
      Ketu: { sign: "Taurus", house: 1 },
    }),
    D7: makeChart("D7", "Pisces", {
      Sun: { sign: "Aries", house: 2 },
      Moon: { sign: "Taurus", house: 3 },
      Mars: { sign: "Libra", house: 8 },
      Mercury: { sign: "Pisces", house: 1 },
      Jupiter: { sign: "Leo", house: 6 },
      Venus: { sign: "Scorpio", house: 9 },
      Saturn: { sign: "Virgo", house: 7 },
      Rahu: { sign: "Sagittarius", house: 10 },
      Ketu: { sign: "Gemini", house: 4 },
    }),
    D8: makeChart("D8", "Capricorn", {
      Sun: { sign: "Gemini", house: 6 },
      Moon: { sign: "Libra", house: 10 },
      Mars: { sign: "Pisces", house: 3 },
      Mercury: { sign: "Taurus", house: 5 },
      Jupiter: { sign: "Aries", house: 4 },
      Venus: { sign: "Sagittarius", house: 12 },
      Saturn: { sign: "Leo", house: 8 },
      Rahu: { sign: "Gemini", house: 6 },
      Ketu: { sign: "Gemini", house: 6 },
    }),
    D9: makeChart("D9", "Scorpio", {
      Sun: { sign: "Cancer", house: 9 },
      Moon: { sign: "Pisces", house: 5 },
      Mars: { sign: "Cancer", house: 9 },
      Mercury: { sign: "Gemini", house: 8 },
      Jupiter: { sign: "Scorpio", house: 1 },
      Venus: { sign: "Capricorn", house: 3 },
      Saturn: { sign: "Cancer", house: 9 },
      Rahu: { sign: "Sagittarius", house: 2 },
      Ketu: { sign: "Gemini", house: 8 },
    }),
    D10: makeChart("D10", "Aries", {
      Sun: { sign: "Leo", house: 5 },
      Moon: { sign: "Leo", house: 5 },
      Mars: { sign: "Sagittarius", house: 9 },
      Mercury: { sign: "Cancer", house: 4 },
      Jupiter: { sign: "Sagittarius", house: 9 },
      Venus: { sign: "Capricorn", house: 10 },
      Saturn: { sign: "Scorpio", house: 8 },
      Rahu: { sign: "Capricorn", house: 10 },
      Ketu: { sign: "Cancer", house: 4 },
    }),
    D11: makeChart("D11", "Leo", {
      Sun: { sign: "Scorpio", house: 4 },
      Moon: { sign: "Aquarius", house: 7 },
      Mars: { sign: "Aries", house: 9 },
      Mercury: { sign: "Virgo", house: 2 },
      Jupiter: { sign: "Aquarius", house: 7 },
      Venus: { sign: "Pisces", house: 8 },
      Saturn: { sign: "Taurus", house: 10 },
      Rahu: { sign: "Capricorn", house: 6 },
      Ketu: { sign: "Cancer", house: 12 },
    }),
    D12: makeChart("D12", "Aries", {
      Sun: { sign: "Aquarius", house: 11 },
      Moon: { sign: "Sagittarius", house: 9 },
      Mars: { sign: "Sagittarius", house: 9 },
      Mercury: { sign: "Sagittarius", house: 9 },
      Jupiter: { sign: "Taurus", house: 2 },
      Venus: { sign: "Gemini", house: 3 },
      Saturn: { sign: "Pisces", house: 12 },
      Rahu: { sign: "Capricorn", house: 10 },
      Ketu: { sign: "Cancer", house: 4 },
    }),
    D20: makeChart("D20", "Aries", {
      Sun: { sign: "Pisces", house: 12 },
      Moon: { sign: "Aquarius", house: 11 },
      Mars: { sign: "Leo", house: 5 },
      Mercury: { sign: "Sagittarius", house: 9 },
      Jupiter: { sign: "Libra", house: 7 },
      Venus: { sign: "Capricorn", house: 10 },
      Saturn: { sign: "Leo", house: 5 },
      Rahu: { sign: "Libra", house: 7 },
      Ketu: { sign: "Libra", house: 7 },
    }),
    D24: makeChart("D24", "Sagittarius", {
      Sun: { sign: "Capricorn", house: 2 },
      Moon: { sign: "Aquarius", house: 3 },
      Mars: { sign: "Taurus", house: 6 },
      Mercury: { sign: "Libra", house: 11 },
      Jupiter: { sign: "Cancer", house: 8 },
      Venus: { sign: "Virgo", house: 10 },
      Saturn: { sign: "Cancer", house: 8 },
      Rahu: { sign: "Pisces", house: 4 },
      Ketu: { sign: "Pisces", house: 4 },
    }),
    D30: makeChart("D30", "Aquarius", {
      Sun: { sign: "Capricorn", house: 12 },
      Moon: { sign: "Virgo", house: 8 },
      Mars: { sign: "Gemini", house: 5 },
      Mercury: { sign: "Pisces", house: 2 },
      Jupiter: { sign: "Pisces", house: 2 },
      Venus: { sign: "Taurus", house: 4 },
      Saturn: { sign: "Taurus", house: 4 },
      Rahu: { sign: "Aquarius", house: 1 },
      Ketu: { sign: "Aquarius", house: 1 },
    }),
    D45: makeChart("D45", "Taurus", {
      Sun: { sign: "Gemini", house: 2 },
      Moon: { sign: "Capricorn", house: 9 },
      Mars: { sign: "Aquarius", house: 10 },
      Mercury: { sign: "Sagittarius", house: 8 },
      Jupiter: { sign: "Cancer", house: 3 },
      Venus: { sign: "Scorpio", house: 7 },
      Saturn: { sign: "Sagittarius", house: 8 },
      Rahu: { sign: "Gemini", house: 2 },
      Ketu: { sign: "Gemini", house: 2 },
    }),
    D60: makeChart("D60", "Aquarius", {
      Sun: { sign: "Aquarius", house: 1 },
      Moon: { sign: "Pisces", house: 2 },
      Mars: { sign: "Leo", house: 7 },
      Mercury: { sign: "Gemini", house: 5 },
      Jupiter: { sign: "Gemini", house: 5 },
      Venus: { sign: "Libra", house: 9 },
      Saturn: { sign: "Pisces", house: 2 },
      Rahu: { sign: "Taurus", house: 4 },
      Ketu: { sign: "Scorpio", house: 10 },
    }),
  },
  planetary_positions: [
    {
      planet: "Sun",
      longitude_deg: 52.746803,
      sign: "Taurus",
      house: 4,
      nakshatra: "Rohini",
      pada: 4,
      retrograde: false,
      combust: false,
      dignity: "enemy",
    },
    {
      planet: "Moon",
      longitude_deg: 159.11182,
      sign: "Virgo",
      house: 8,
      nakshatra: "Uttara Phalguni",
      pada: 4,
      retrograde: false,
      combust: false,
      dignity: "friendly",
    },
    {
      planet: "Mars",
      longitude_deg: 132.402656,
      sign: "Leo",
      house: 7,
      nakshatra: "Magha",
      pada: 4,
      retrograde: false,
      combust: false,
      dignity: "friendly",
    },
    {
      planet: "Mercury",
      longitude_deg: 48.931461,
      sign: "Taurus",
      house: 4,
      nakshatra: "Rohini",
      pada: 3,
      retrograde: true,
      combust: true,
      dignity: "friendly",
    },
    {
      planet: "Jupiter",
      longitude_deg: 225.921299,
      sign: "Scorpio",
      house: 10,
      nakshatra: "Anuradha",
      pada: 4,
      retrograde: true,
      combust: false,
      dignity: "friendly",
    },
    {
      planet: "Venus",
      longitude_deg: 32.661952,
      sign: "Taurus",
      house: 4,
      nakshatra: "Krittika",
      pada: 2,
      retrograde: false,
      combust: false,
      dignity: "own",
    },
    {
      planet: "Saturn",
      longitude_deg: 330.281061,
      sign: "Pisces",
      house: 2,
      nakshatra: "Purva Bhadrapada",
      pada: 4,
      retrograde: false,
      combust: false,
      dignity: "neutral",
    },
    {
      planet: "Rahu",
      longitude_deg: 189.616964,
      sign: "Libra",
      house: 9,
      nakshatra: "Swati",
      pada: 1,
      retrograde: true,
      combust: false,
      dignity: "neutral",
    },
    {
      planet: "Ketu",
      longitude_deg: 9.616964,
      sign: "Aries",
      house: 3,
      nakshatra: "Ashwini",
      pada: 3,
      retrograde: true,
      combust: false,
      dignity: "neutral",
    },
  ],
  aspects: [],
  yogas: [
    {
      name: "Raja Yoga",
      confidence: "medium",
      source_charts: ["D1"],
      planets_involved: ["Sun", "Venus"],
      notes: ["Kendra lord Sun conjunct trikona lord Venus in house 4"],
    },
    {
      name: "Raja Yoga",
      confidence: "medium",
      source_charts: ["D1"],
      planets_involved: ["Mercury", "Sun"],
      notes: ["Kendra lord Sun conjunct trikona lord Mercury in house 4"],
    },
    {
      name: "Raja Yoga",
      confidence: "medium",
      source_charts: ["D1"],
      planets_involved: ["Mercury", "Venus"],
      notes: ["Kendra lord Venus conjunct trikona lord Mercury in house 4"],
    },
    {
      name: "Dhana Yoga",
      confidence: "medium",
      source_charts: ["D1"],
      planets_involved: ["Mercury", "Venus"],
      notes: ["Dhana lords Venus & Mercury conjunct in house 4"],
    },
  ],
  dasha: {
    system: "vimshottari",
    current_mahadasha: { lord: "Rahu", start: "2012-10-30", end: "2030-10-31" },
    current_antardasha: { lord: "Saturn", start: "2017-12-06", end: "2020-10-12" },
    upcoming: [
      { lord: "Jupiter", start: "2030-10-31", end: "2046-10-31" },
      { lord: "Saturn", start: "2046-10-31", end: "2065-10-30" },
      { lord: "Mercury", start: "2065-10-30", end: "2082-10-30" },
    ],
  },
  transits: {
    as_of: "2020-01-01T00:00:00+00:00",
    positions: [],
    highlights: [],
  },
  lagna_longitude_deg: 306.2177,
};
